# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- resources.yaml
configMapGenerator:
- name: parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
configurations:
- params.yaml