apiVersion: v1alpha1
kind: RegistryReplace
metadata:
  name: myTransformer
spec:
  fieldSpecs:
  - kind: Deployment
    group: apps
    version: v1
    path: spec/template/spec/containers[]/image
  - kind: ImageStream
    group: image.openshift.io
    version: v1
    path: spec/tags[]/from/name
  - kind: ImageStream
    group: image.openshift.io
    version: v1
    path: spec/tags[]/annotations/openshift.io\/imported-from
  - kind: ConfigMap
    version: v1
    path: data/image
  - kind: ConfigMap
    version: v1
    path: data/someTextField
  - kind: Job
    version: v1
    group: batch
    path: spec/template/spec/containers[]/image
  registries:
  - src: quay.io
    dest: private-registry.example.com
  - src: docker.io
    dest: private-registry.example.com
  - src: gcr.io
    dest: private-registry.example.com
  imageListOutput:
    file: /tmp/images2.yaml